@Shorty_HostAddress = http://localhost:5016

POST {{Shorty_HostAddress}}/Url/ShortenUrl
Content-Type: application/json
"https://ferrets.com/toys/puzzles?item=Akr45"

###

POST {{Shorty_HostAddress}}/Url/ShortenUrl
Content-Type: application/json
"bad.url.com"

###

POST {{Shorty_HostAddress}}/Url/ExpandUrl
Content-Type: application/json
"https://shorty.com/G3KUATicBXurP2Pj"

###

POST {{Shorty_HostAddress}}/Url/ExpandUrl
Content-Type: application/json
"https://shorty.com/UNKNOWN"

###